INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_NAME,
    MEMBER_PHONE, MEMBER_AGE, MEMBER_PURPOSE, MEMBER_CONCERN, MEMBER_TRAINER, MEMBER_ABSENCE, MEMBER_JOIN_DATE) VALUES(
    (SELECT nvl(max(member_no),0)+1 from tb_member), 'admin1', '1234', 'nickname1', 'admin1@gmail.com', '서유빈', '010-0000-0000', 18, 
    1, 1, DEFAULT, DEFAULT, DEFAULT);
    
INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_NAME,
    MEMBER_PHONE, MEMBER_AGE, MEMBER_PURPOSE, MEMBER_CONCERN, MEMBER_TRAINER, MEMBER_ABSENCE, MEMBER_JOIN_DATE) VALUES(
    (SELECT nvl(max(member_no),0)+1 from tb_member), 'admin2', '1234', 'nickname2', 'admin2@gmail.com', '민승택', '010-0000-0000', 3, 
    1, 1, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_NAME,
    MEMBER_PHONE, MEMBER_AGE, MEMBER_PURPOSE, MEMBER_CONCERN, MEMBER_TRAINER, MEMBER_ABSENCE, MEMBER_JOIN_DATE) VALUES(
    (SELECT nvl(max(member_no),0)+1 from tb_member), 'admin3', '1234', 'nickname3', 'admin3@gmail.com', '박재민', '010-0000-0000', 26, 
    1, 1, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_NAME,
    MEMBER_PHONE, MEMBER_AGE, MEMBER_PURPOSE, MEMBER_CONCERN, MEMBER_TRAINER, MEMBER_ABSENCE, MEMBER_JOIN_DATE) VALUES(
    (SELECT nvl(max(member_no),0)+1 from tb_member), 'admin4', '1234', 'nickname4', 'admin4@gmail.com', '이진정', '010-0000-0000', 30, 
    1, 1, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO TB_EXERCISE (EXERCISE_NO, EXERCISE_NAME, EXERCISE_PART, EXERCISE_AEROBIC) 
    VALUES ((SELECT nvl(max(EXERCISE_NO),0)+1 from TB_EXERCISE), '스쿼트', 'L', 'F');
    
INSERT INTO TB_EXERCISE (EXERCISE_NO, EXERCISE_NAME, EXERCISE_PART, EXERCISE_AEROBIC) 
    VALUES ((SELECT nvl(max(EXERCISE_NO),0)+1 from TB_EXERCISE), '데드리프트', 'F', 'F');
    
INSERT INTO TB_EXERCISE (EXERCISE_NO, EXERCISE_NAME, EXERCISE_PART, EXERCISE_AEROBIC) 
    VALUES ((SELECT nvl(max(EXERCISE_NO),0)+1 from TB_EXERCISE), '벤치프레스', 'C', 'F');

INSERT INTO TB_ROUTINE (ROUTINE_NO, MEMBER_NO, ROUTINE_NAME, ROUTINE_DISABLE) 
    VALUES ((SELECT nvl(max(ROUTINE_NO),0)+1 from TB_ROUTINE), 1, '서유빈루틴', DEFAULT);

INSERT INTO TB_ROUTINE (ROUTINE_NO, MEMBER_NO, ROUTINE_NAME, ROUTINE_DISABLE) 
    VALUES ((SELECT nvl(max(ROUTINE_NO),0)+1 from TB_ROUTINE), 2, '민승택루틴', DEFAULT);

INSERT INTO TB_ROUTINE (ROUTINE_NO, MEMBER_NO, ROUTINE_NAME, ROUTINE_DISABLE) 
    VALUES ((SELECT nvl(max(ROUTINE_NO),0)+1 from TB_ROUTINE), 3, '박재민루틴', DEFAULT);

INSERT INTO TB_ROUTINE_EXERCISE (ROUTINE_EXERCISE_NO, EXERCISE_NO, ROUTINE_NO, ROUTINE_EXERCISE_DAY,
    ROUTINE_WEEK, ROUTINE_DAY, ROUTINE_EXERCISE_SET, ROUTINE_EXERCISE_REPEAT, ROUTINE_EXERCISE_WEIGHT, 
    ROUTINE_EXERCISE_TIME, ROUTINE_EXERCISE_DISTANCE, ROUTINE_EXERCISE_PERFORM_DAY, ROUTINE_EXERCISE_D_DAY, ROUTINE_EXERCISE_SEQUENCE)
    VALUES ((SELECT nvl(max(ROUTINE_EXERCISE_NO),0)+1 from TB_ROUTINE_EXERCISE), 1, 1, 1, 1, 1, 1, 10, 50, 
    null, null, systimestamp, systimestamp, 1);
    
INSERT INTO TB_ROUTINE_EXERCISE (ROUTINE_EXERCISE_NO, EXERCISE_NO, ROUTINE_NO, ROUTINE_EXERCISE_DAY,
    ROUTINE_WEEK, ROUTINE_DAY, ROUTINE_EXERCISE_SET, ROUTINE_EXERCISE_REPEAT, ROUTINE_EXERCISE_WEIGHT, 
    ROUTINE_EXERCISE_TIME, ROUTINE_EXERCISE_DISTANCE, ROUTINE_EXERCISE_PERFORM_DAY, ROUTINE_EXERCISE_D_DAY, ROUTINE_EXERCISE_SEQUENCE)
    VALUES ((SELECT nvl(max(ROUTINE_EXERCISE_NO),0)+1 from TB_ROUTINE_EXERCISE), 1, 1, 1, 1, 1, 2, 10, 50, 
    null, null, systimestamp, systimestamp, 1);
    
INSERT INTO TB_ROUTINE_EXERCISE (ROUTINE_EXERCISE_NO, EXERCISE_NO, ROUTINE_NO, ROUTINE_EXERCISE_DAY,
    ROUTINE_WEEK, ROUTINE_DAY, ROUTINE_EXERCISE_SET, ROUTINE_EXERCISE_REPEAT, ROUTINE_EXERCISE_WEIGHT, 
    ROUTINE_EXERCISE_TIME, ROUTINE_EXERCISE_DISTANCE, ROUTINE_EXERCISE_PERFORM_DAY, ROUTINE_EXERCISE_D_DAY, ROUTINE_EXERCISE_SEQUENCE)
    VALUES ((SELECT nvl(max(ROUTINE_EXERCISE_NO),0)+1 from TB_ROUTINE_EXERCISE), 1, 1, 1, 1, 1, 3, 10, 50, 
    null, null, systimestamp, systimestamp, 1);







INSERT INTO TB_EXERCISE_RECORD (RECORD_NO, RECORD_START, RECORD_STOP, MEMBER_NO, ROUTINE_EXERCISE_NO) 
    VALUES ((SELECT nvl(max(RECORD_NO),0)+1 from TB_EXERCISE_RECORD), DEFAULT, DEFAULT, 1, 1);






















