
INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_EMAIL, 
    MEMBER_PHONE, MEMBER_AGE, MEMBER_PURPOSE_NAME, MEMBER_CONCERN_NAME, MEMBER_TRAINER, MEMBER_ABSENCE, MEMBER_JOIN_DATE) VALUES(
    (SELECT nvl(max(member_no),0)+1 from tb_member), 'admin1', '1234', 'nickname1', 'admin1@gmail.com', '서유빈', '010-0000-0000', 18, 
    1, 1, DEFAULT, DEFAULT, DEFAULT);
    
