
DROP TABLE TB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_EXERCISE CASCADE CONSTRAINTS;
DROP TABLE TB_EXERCISE_RECORD CASCADE CONSTRAINTS;
DROP TABLE TB_ROUTINE CASCADE CONSTRAINTS;
DROP TABLE TB_PT CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD CASCADE CONSTRAINTS;
DROP TABLE TB_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_ROUTINE_EXERCISE CASCADE CONSTRAINTS;
DROP TABLE TB_TRAINER CASCADE CONSTRAINTS;
DROP TABLE TB_BLACKLIST CASCADE CONSTRAINTS;
DROP TABLE TB_FAVORITE CASCADE CONSTRAINTS;
DROP TABLE TB_REVIEW CASCADE CONSTRAINTS;
DROP TABLE TB_TRADE CASCADE CONSTRAINTS;
DROP TABLE TB_LETTER CASCADE CONSTRAINTS;
DROP TABLE TB_MEMBER_BACKUP CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD_BACKUP CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD_REPORT CASCADE CONSTRAINTS;
DROP TABLE TB_COMMENT_REPORT CASCADE CONSTRAINTS;
DROP TABLE TB_RECOMMENT_BACKUP CASCADE CONSTRAINTS;
DROP TABLE TB_PT_FILE CASCADE CONSTRAINTS;
DROP TABLE TB_REPORT_BACKUP CASCADE CONSTRAINTS;
DROP TABLE TB_PT_CALENDAR CASCADE CONSTRAINTS;
DROP TABLE TB_VISIT CASCADE CONSTRAINTS;
DROP TABLE TB_EMAIL_CERTIFICATION CASCADE CONSTRAINTS;











CREATE TABLE TB_MEMBER (
	MEMBER_NO	NUMBER		NOT NULL,
	MEMBER_ID VARCHAR2(20)		NOT NULL,
	MEMBER_PASSWORD	VARCHAR2(20)		NOT NULL,
	MEMBER_NICKNAME	VARCHAR2(20)		NOT NULL,
	MEMBER_EMAIL	VARCHAR2(100)		NOT NULL,
	MEMBER_NAME	VARCHAR2(20)		NOT NULL,
	MEMBER_PHONE	VARCHAR2(13)		NOT NULL,
	MEMBER_AGE	NUMBER		NOT NULL,
	MEMBER_PURPOSE	NUMBER		NOT NULL,
	MEMBER_CONCERN	NUMBER		NOT NULL,
	MEMBER_PHOTO	BLOB		NULL,
	MEMBER_TRAINER	VARCHAR2(1)	DEFAULT 'F' NOT NULL,
	MEMBER_ABSENCE	VARCHAR2(1)	DEFAULT 'N' NOT NULL,
	MEMBER_JOIN_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MEMBER_LEAVE_DATE	DATE		NULL
);

COMMENT ON COLUMN TB_MEMBER.MEMBER_PURPOSE IS '선택안함, 감량, 증량, 체력관리, 바디프로필, 기타';

COMMENT ON COLUMN TB_MEMBER.MEMBER_CONCERN IS '선택안함, 웨이트트레이닝, 필라테스, 요가, 기타';

COMMENT ON COLUMN TB_MEMBER.MEMBER_TRAINER IS 'T: 트레이너 F: 일반회원 R: from 트레이너 to 일반 회원 전환중';



CREATE TABLE TB_EXERCISE (
	EXERCISE_NO	NUMBER		NOT NULL,
	EXERCISE_NAME	VARCHAR2(50)		NOT NULL,
	EXERCISE_PART	CHAR(1)		NOT NULL,
	EXERCISE_AEROBIC	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN TB_EXERCISE.EXERCISE_AEROBIC IS 'T: 유산소F: 무산소,U:무관';



CREATE TABLE TB_EXERCISE_RECORD (
	RECORD_NO	NUMBER		NOT NULL,
	RECORD_START	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	RECORD_STOP	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	ROUTINE_EXERCISE_NO	NUMBER		NULL
);


CREATE TABLE TB_ROUTINE (
	ROUTINE_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	ROUTINE_NAME	VARCHAR2(20)		NOT NULL,
	ROUTINE_DISABLE	CHAR(1)	DEFAULT 'F'	NOT NULL
);

COMMENT ON COLUMN TB_ROUTINE.ROUTINE_NAME IS '루틴이름';

COMMENT ON COLUMN TB_ROUTINE.ROUTINE_DISABLE IS 'T: 사용불가 리스트에 표시안됨
F: 사용가능 리스트에 표시됨';


CREATE TABLE TB_PT (
	PT_NO	NUMBER		NOT NULL,
	TRAINER_NO	NUMBER		NOT NULL,
	PT_NAME	VARCHAR2(30)		NOT NULL,
	PT_CATEGORY	NUMBER		NOT NULL,
	PT_PRICE	NUMBER		NOT NULL,
	PT_INTRODUCE	VARCHAR2(3000)		NOT NULL,
	PT_INFORMATION	VARCHAR2(3000)		NOT NULL,
	PT_TARGET_STUDENT	VARCHAR2(600)		NOT NULL,
	PT_NOTICE	VARCHAR2(600)		NOT NULL
);

COMMENT ON COLUMN TB_PT.PT_CATEGORY IS '1웨이트, 2:채중감량,3:재활';

COMMENT ON COLUMN TB_PT.PT_PRICE IS '단위 원';


CREATE TABLE TB_BOARD (
	BOARD_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	BOARD_TITLE	VARCHAR2(200)		NOT NULL,
	BOARD_CONTENT	VARCHAR2(1000)		NOT NULL,
	BOARD_COUNT	NUMBER	DEFAULT 0	NOT NULL,
	BOARD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	BOARD_TYPE	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN TB_BOARD.BOARD_TYPE IS '1:전체,2:자유,3:루틴';


CREATE TABLE TB_COMMENT (
	COMMENT_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	COMMENT_CONTENT	VARCHAR2(300)		NOT NULL,
	COMMENT_DATE	DATE	DEFAULT sysdate	NOT NULL,
	COMMENT_EDIT_DATE	DATE	DEFAULT sysdate	NULL
);


CREATE TABLE TB_ROUTINE_EXERCISE (
	ROUTINE_EXERCISE_NO	NUMBER		NOT NULL,
	EXERCISE_NO	NUMBER		NOT NULL,
    ROUTINE_NO	NUMBER		NOT NULL,
	ROUTINE_EXERCISE_DAY	NUMBER		NOT NULL,
	ROUTINE_WEEK	NUMBER		NOT NULL,
	ROUTINE_DAY	NUMBER		NOT NULL,
	ROUTINE_EXERCISE_SET	NUMBER		NULL,
	ROUTINE_EXERCISE_REPEAT	NUMBER		NULL,
	ROUTINE_EXERCISE_WEIGHT	NUMBER		NULL,
	ROUTINE_EXERCISE_TIME	NUMBER		NULL,
	ROUTINE_EXERCISE_DISTANCE	NUMBER		NULL,
	ROUTINE_EXERCISE_PERFORM_DAY	TIMESTAMP		NULL,
	ROUTINE_EXERCISE_D_DAY	TIMESTAMP		NULL,
	ROUTINE_EXERCISE_SEQUENCE	NUMBER		NULL
);

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_NO IS '루틴의 몇번째 운동인지';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_DAY IS 'DOMAIN:MON, THU,..요일만 가능 ROUTINE_DAY랑 겹침?';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_NO IS '기본키랑 겹침?';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_SET IS '근력운동일때 입력';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_REPEAT IS '근력운동일때 입력';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_WEIGHT IS '근력운동일때 입력
단위:kg';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_TIME IS '유산소 운동중 시간으로 운동량이 결정되는 경우 단위: 분';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_DISTANCE IS '유산소 운동중 거리로 운동량이 결정되는 경우 단위: m';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_PERFORM_DAY IS '운동기록 테이블을 참조하면 알수 있지않나?';

COMMENT ON COLUMN TB_ROUTINE_EXERCISE.ROUTINE_EXERCISE_D_DAY IS '운동기록 테이블을 참조하면 알 수 잇지않나?';


CREATE TABLE TB_TRAINER (
	TRAINER_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	TRAINER_FILE	BLOB		NULL,
	TRAINER_CONFIRM	VARCHAR(1)	DEFAULT 'R'	NOT NULL,
	GYM_NAME	VARCHAR(255)		NOT NULL,
	GYM_LOCATION	VARCHAR(255)		NOT NULL,
	TRAINER_ETR	DATE		NULL
);

COMMENT ON COLUMN TB_TRAINER.TRAINER_FILE IS 'URL';

COMMENT ON COLUMN TB_TRAINER.TRAINER_CONFIRM IS 'T 인증 완료, F 인증 실패,  R 관리자 확인 중';



CREATE TABLE TB_BLACKLIST (
	BLACK_LIST_NO	NUMBER		NOT NULL,
	TRAINER_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL
);


CREATE TABLE TB_FAVORITE (
	FAVORITE_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL
);


CREATE TABLE TB_REVIEW (
	REVIEW_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	PT_NO	NUMBER		NOT NULL,
	REVIEW_CONTENT	VARCHAR2(100)		NOT NULL
);


CREATE TABLE TB_TRADE (
	TRADE_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	PT_NO	NUMBER		NOT NULL,
	TRADE_METHOD	NUMBER		NOT NULL,
	TRADE_TIME	TIMESTAMP		NOT NULL,
	TRADE_PRICE	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_TRADE.MEMBER_NO IS '결재한 사람';

COMMENT ON COLUMN TB_TRADE.PT_NO IS 'PT 프로그램의 트레이너가 돈을 받음';

COMMENT ON COLUMN TB_TRADE.TRADE_METHOD IS 'NUMBER이면
1: 실시간 입금
2: 무통장 입금
3: 카드 결제
VARCHAR2(30)
텍스트로 입력';

COMMENT ON COLUMN TB_TRADE.TRADE_PRICE IS '단위: 원';


CREATE TABLE TB_LETTER (
	LETTER_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	LETTER_CONTENT	VARCHAR2(1000)		NOT NULL,
	LETTER_SEND_TIME	TIMESTAMP		NOT NULL,
	LETTER_READ	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	LETTER_READ_TIME	TIMESTAMP		NULL
);

COMMENT ON COLUMN TB_LETTER.LETTER_READ IS 'Y: 읽음
N: 안읽음';


CREATE TABLE TB_MEMBER_BACKUP (
	MEMBER_NO	NUMBER		NOT NULL,
	MEMBER_ID	VARCHAR2(20)		NOT NULL,
	MEMBER_PASSWORD	VARCHAR2(20)		NOT NULL,
	MEMBER_NICKNAME	VARCHAR2(20)		NOT NULL,
	MEMBER_EMAIL	VARCHAR2(100)		NOT NULL,
	MEMBER_NAME	VARCHAR2(20)		NOT NULL,
	MEMBER_PHONE	VARCHAR2(13)		NOT NULL,
	MEMBER_AGE	NUMBER		NULL,
	PURPOSE_NAME	VARCHAR2(20)		NULL,
	CONCERN_NAME	VARCHAR2(20)		NULL,
	MEMBER_PHOTO	BLOB		NULL,
	MEMBER_TRAINER	VARCHAR2(1)	DEFAULT 'F'	NOT NULL,
	MEMBER_STATE	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	MEMBER_JOIN_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MEMBER_LEAVE_DATE	DATE		NULL
);

COMMENT ON COLUMN TB_MEMBER_BACKUP.MEMBER_TRAINER IS 'T: 트레이너F: 일반회원';



CREATE TABLE TB_BOARD_BACKUP (
	BOARD_BACKUP_NO	NUMBER		NOT NULL,
	BOARD_BACKUP_WRITER	NUMBER		NOT NULL,
	BOARD_BACKUP_TITLE	VARCHAR2(200)		NOT NULL,
	BOARD_BACKUP_CONTENT	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN TB_BOARD_BACKUP.BOARD_BACKUP_NO IS 'TB_BOARD BOARD_NO값이 입력됨';


CREATE TABLE TB_BOARD_REPORT (
	BOARD_REPORT_NO	VARCHAR(255)		NOT NULL,
	BOARD_REPORT_CONTENT	VARCHAR2(300)		NOT NULL,
	BOARD_REPORT_TIME	TIMESTAMP		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL
);


CREATE TABLE TB_COMMENT_REPORT (
	COMMENT_REPORT_NO	NUMBER		NOT NULL,
	COMMENT_REPORT_CONTENT	VARCHAR2(300)		NOT NULL,
	COMMENT_REPORT_DATE	DATE		NOT NULL,
	COMMENT_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL
);


CREATE TABLE TB_RECOMMENT_BACKUP (
	RECOMMNET_BACKUP_NO	NUMBER		NOT NULL,
	RECOMMENT_BACKUP_WRITIER	NUMBER		NOT NULL,
	RECOMMNET_BACKUP_CONTENT	VARCHAR(255)		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_RECOMMENT_BACKUP.RECOMMNET_BACKUP_NO IS 'TB_RECOMMNET RECOMMNET_NO값이 입력됨';


CREATE TABLE TB_PT_FILE (
	PT_FILE_NO	NUMBER		NOT NULL,
	PT_NO	NUMBER		NOT NULL,
	PT_FILE	BLOB		NOT NULL
);





CREATE TABLE TB_REPORT_BACKUP (
	REPORT_BACKUP_NO	NUMBER		NOT NULL,
	REPORT_BACKUP_REPORTER	NUMBER		NOT NULL,
	REPORT_BACKUP_CONTENT	VARCHAR2(300)		NOT NULL,
	REPORT_BACKUP_TIME	TIMESTAMP		NOT NULL,
	BOARD_BACKUP_NO	NUMBER		NOT NULL,
	RECOMMNET_BACKUP_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_REPORT_BACKUP.BOARD_BACKUP_NO IS 'TB_BOARD BOARD_NO값이 입력됨';

COMMENT ON COLUMN TB_REPORT_BACKUP.RECOMMNET_BACKUP_NO IS 'TB_RECOMMNET RECOMMNET_NO값이 입력됨';


CREATE TABLE TB_PT_CALENDAR (
	PT_CALENDAR_NO	NUMBER		NOT NULL,
	PT_NO	NUMBER		NOT NULL,
    MEMBER_NO	NUMBER		NOT NULL,
	PT_CALENDAR_START_TIME	TIMESTAMP		NOT NULL,
	PT_CALENDAR_RESERVATION_STATE	CHAR(1)	DEFAULT 'F'	NOT NULL
);

COMMENT ON COLUMN TB_PT_CALENDAR.PT_CALENDAR_RESERVATION_STATE IS 'T: 예약됨 F: 예약안됨';


CREATE TABLE TB_VISIT (
	VISIT_NO	NUMBER		NOT NULL,
	VISIT_IP	VARCHAR2(15)		NOT NULL,
	VISIT_TIME	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN TB_VISIT.VISIT_IP IS 'FORMAT: 000.000.000.000';


CREATE TABLE TB_EMAIL_CERTIFICATION (
	EMAIL_CERTIFICATION_NO	VARCHAR(255)		NOT NULL,
	EMAIL_CERTIFICATION_EMAIL	VARCHAR2(100)		NOT NULL,
	EMAIL_CERTIFICATION_CODE	VARCHAR2(6)		NOT NULL
);

ALTER TABLE TB_MEMBER ADD CONSTRAINT PK_TB_MEMBER PRIMARY KEY (
	MEMBER_NO
);

ALTER TABLE TB_EXERCISE ADD CONSTRAINT PK_TB_EXERCISE PRIMARY KEY (
	EXERCISE_NO
);

ALTER TABLE TB_EXERCISE_RECORD ADD CONSTRAINT PK_TB_EXERCISE_RECORD PRIMARY KEY (
	RECORD_NO
);

ALTER TABLE TB_ROUTINE ADD CONSTRAINT PK_TB_ROUTINE PRIMARY KEY (
	ROUTINE_NO
);

ALTER TABLE TB_PT ADD CONSTRAINT PK_TB_PT PRIMARY KEY (
	PT_NO
);

ALTER TABLE TB_BOARD ADD CONSTRAINT PK_TB_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE TB_COMMENT ADD CONSTRAINT PK_TB_COMMENT PRIMARY KEY (
	COMMENT_NO
);

ALTER TABLE TB_ROUTINE_EXERCISE ADD CONSTRAINT PK_TB_ROUTINE_EXERCISE PRIMARY KEY (
	ROUTINE_EXERCISE_NO
);

ALTER TABLE TB_TRAINER ADD CONSTRAINT PK_TB_TRAINER PRIMARY KEY (
	TRAINER_NO
);

ALTER TABLE TB_BLACKLIST ADD CONSTRAINT PK_TB_BLACKLIST PRIMARY KEY (
	BLACK_LIST_NO
);

ALTER TABLE TB_FAVORITE ADD CONSTRAINT PK_TB_FAVORITE PRIMARY KEY (
	FAVORITE_NO
);

ALTER TABLE TB_REVIEW ADD CONSTRAINT PK_TB_REVIEW PRIMARY KEY (
	REVIEW_NO
);

ALTER TABLE TB_TRADE ADD CONSTRAINT PK_TB_TRADE PRIMARY KEY (
	TRADE_NO
);

ALTER TABLE TB_LETTER ADD CONSTRAINT PK_TB_LETTER PRIMARY KEY (
	LETTER_NO
);

ALTER TABLE TB_MEMBER_BACKUP ADD CONSTRAINT PK_TB_MEMBER_BACKUP PRIMARY KEY (
	MEMBER_NO
);

ALTER TABLE TB_BOARD_BACKUP ADD CONSTRAINT PK_TB_BOARD_BACKUP PRIMARY KEY (
	BOARD_BACKUP_NO
);

ALTER TABLE TB_BOARD_REPORT ADD CONSTRAINT PK_TB_BOARD_REPORT PRIMARY KEY (
	BOARD_REPORT_NO
);

ALTER TABLE TB_COMMENT_REPORT ADD CONSTRAINT PK_TB_COMMENT_REPORT PRIMARY KEY (
	COMMENT_REPORT_NO
);

ALTER TABLE TB_RECOMMENT_BACKUP ADD CONSTRAINT PK_TB_RECOMMENT_BACKUP PRIMARY KEY (
	RECOMMNET_BACKUP_NO
);

ALTER TABLE TB_PT_FILE ADD CONSTRAINT PK_TB_PT_FILE PRIMARY KEY (
	PT_FILE_NO
);

ALTER TABLE TB_REPORT_BACKUP ADD CONSTRAINT PK_TB_REPORT_BACKUP PRIMARY KEY (
	REPORT_BACKUP_NO
);

ALTER TABLE TB_PT_CALENDAR ADD CONSTRAINT PK_TB_PT_CALENDAR PRIMARY KEY (
	PT_CALENDAR_NO
);

ALTER TABLE TB_VISIT ADD CONSTRAINT PK_TB_VISIT PRIMARY KEY (
	VISIT_NO
);

ALTER TABLE TB_EMAIL_CERTIFICATION ADD CONSTRAINT PK_TB_EMAIL_CERTIFICATION PRIMARY KEY (
	EMAIL_CERTIFICATION_NO
);

ALTER TABLE TB_EXERCISE_RECORD ADD CONSTRAINT FK_TB_MEMBER_TO FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_EXERCISE_RECORD ADD CONSTRAINT FK_TB_ROUTINE_EXERCISE_TO FOREIGN KEY (
	ROUTINE_EXERCISE_NO
)
REFERENCES TB_ROUTINE_EXERCISE (
	ROUTINE_EXERCISE_NO
);

ALTER TABLE TB_ROUTINE ADD CONSTRAINT FK_TB_MEMBER_TO_TB_ROUTINE_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_PT ADD CONSTRAINT FK_TB_TRAINER_TO_TB_PT_1 FOREIGN KEY (
	TRAINER_NO
)
REFERENCES TB_TRAINER (
	TRAINER_NO
);

ALTER TABLE TB_BOARD ADD CONSTRAINT FK_TB_MEMBER_TO_TB_BOARD_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_COMMENT ADD CONSTRAINT FK_TB_BOARD_TO_TB_COMMENT_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES TB_BOARD (
	BOARD_NO
);

ALTER TABLE TB_COMMENT ADD CONSTRAINT FK_TB_MEMBER_TO_TB_COMMENT_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_ROUTINE_EXERCISE ADD CONSTRAINT FK_TB_EXERCISE_TO FOREIGN KEY (
	EXERCISE_NO
)
REFERENCES TB_EXERCISE (
	EXERCISE_NO
);

ALTER TABLE TB_ROUTINE_EXERCISE ADD CONSTRAINT FK_TB_ROUTINE FOREIGN KEY (
	ROUTINE_NO
)
REFERENCES TB_ROUTINE (
	ROUTINE_NO
);

ALTER TABLE TB_TRAINER ADD CONSTRAINT FK_TB_MEMBER_TO_TB_TRAINER_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_BLACKLIST ADD CONSTRAINT FK_TB_TRAINER_TO_TB_BLACKLIST FOREIGN KEY (
	TRAINER_NO
)
REFERENCES TB_TRAINER (
	TRAINER_NO
);

ALTER TABLE TB_BLACKLIST ADD CONSTRAINT FK_TB_MEMBER_TO_TB_BLACKLIST_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_FAVORITE ADD CONSTRAINT FK_TB_BOARD_TO_TB_FAVORITE_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES TB_BOARD (
	BOARD_NO
);

ALTER TABLE TB_FAVORITE ADD CONSTRAINT FK_TB_MEMBER_TO_TB_FAVORITE_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_REVIEW ADD CONSTRAINT FK_TB_MEMBER_TO_TB_REVIEW_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_REVIEW ADD CONSTRAINT FK_TB_PT_TO_TB_REVIEW_1 FOREIGN KEY (
	PT_NO
)
REFERENCES TB_PT (
	PT_NO
);

ALTER TABLE TB_TRADE ADD CONSTRAINT FK_TB_MEMBER_TO_TB_TRADE_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_TRADE ADD CONSTRAINT FK_TB_PT_TO_TB_TRADE_1 FOREIGN KEY (
	PT_NO
)
REFERENCES TB_PT (
	PT_NO
);

ALTER TABLE TB_LETTER ADD CONSTRAINT FK_TB_MEMBER_TO_TB_LETTER FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_BOARD_REPORT ADD CONSTRAINT FK_TB_BOARD_TO_TB_BOARD_REPORT FOREIGN KEY (
	BOARD_NO
)
REFERENCES TB_BOARD (
	BOARD_NO
);

ALTER TABLE TB_BOARD_REPORT ADD CONSTRAINT FK_TB_MEMBER FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_COMMENT_REPORT ADD CONSTRAINT FK_TB_COMMENT FOREIGN KEY (
	COMMENT_NO
)
REFERENCES TB_COMMENT (
	COMMENT_NO
);

ALTER TABLE TB_COMMENT_REPORT ADD CONSTRAINT FK_TB_MEMBER_TO_MEMBER FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);

ALTER TABLE TB_PT_FILE ADD CONSTRAINT FK_TB_PT_TO_TB_PT_FILE_1 FOREIGN KEY (
	PT_NO
)
REFERENCES TB_PT (
	PT_NO
);

ALTER TABLE TB_REPORT_BACKUP ADD CONSTRAINT FK_TB_BOARD_BACKUP FOREIGN KEY (
	BOARD_BACKUP_NO
)
REFERENCES TB_BOARD_BACKUP (
	BOARD_BACKUP_NO
);

ALTER TABLE TB_REPORT_BACKUP ADD CONSTRAINT RECOMMENT_BACKUP FOREIGN KEY (
	RECOMMNET_BACKUP_NO
)
REFERENCES TB_RECOMMENT_BACKUP (
	RECOMMNET_BACKUP_NO
);

ALTER TABLE TB_PT_CALENDAR ADD CONSTRAINT FK_TB_PT_TO_TB_PT_CALENDAR_1 FOREIGN KEY (
	PT_NO
)
REFERENCES TB_PT (
	PT_NO
);

ALTER TABLE TB_PT_CALENDAR ADD CONSTRAINT FK_TB_MEMBER_TO_TB_PT_CALENDAR FOREIGN KEY (
	MEMBER_NO
)
REFERENCES TB_MEMBER (
	MEMBER_NO
);


