DROP TABLE IF EXISTS 'TB_MEMBER';

CREATE TABLE `TB_MEMBER` (
	`MEMBER_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`MEMBER_PASSWORD`	VARCHAR2(20)	NOT NULL,
	`MEMBER_NICKNAME`	VARCHAR2(20)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR2(100)	NOT NULL,
	`MEMBER_NAME`	VARCHAR2(20)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR2(13)	NOT NULL,
	`MEMBER_AGE`	NUMBER	NULL,
	`PURPOSE_NAME`	VARCHR2(20)	NULL,
	`CONCERN_NAME`	VARCHR2(20)	NULL,
	`MEMBER_PHOTO`	LOB	NULL,
	`MEMBER_TRAINER`	VARCAHR2(1)	NOT NULL	DEFAULT F	COMMENT 'T: 트레이너F: 일반회원',
	`MEMBER_STATE`	VARCHAR2(1)	NOT NULL	DEFAULT N,
	`MEMBER_JOIN_DATE`	SYSDATE	NOT NULL	DEFAULT SYSDATE,
	`MEMBER_LEAVE_DATE`	DATE	NULL
);

DROP TABLE IF EXISTS `TB_EXERCISE`;

CREATE TABLE `TB_EXERCISE` (
	`EXERCISE_NO`	NUMBER	NOT NULL,
	`EXERCISE_NAME`	VARCHAR2(50)	NOT NULL,
	`EXERCISE_PART`	VARCHAR2(20)	NOT NULL,
	`EXERCISE_AEROBIC`	CHAR(1)	NOT NULL	DEFAULT U	COMMENT 'T: 유산소F: 무산소,U:무관'
);

DROP TABLE IF EXISTS `TB_EXERCISE_RECORD`;

CREATE TABLE `TB_EXERCISE_RECORD` (
	`RECORD_NO`	NUMBER	NOT NULL,
	`RECORD_START`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`RECORD_STOP`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`EXERCISE_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`ROUTINE_EXERCISE_NO`	NUMBER	NULL
);

DROP TABLE IF EXISTS `TB_ROUTINE`;

CREATE TABLE `TB_ROUTINE` (
	`ROUTINE_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`ROUTINE_NAME`	VARCHAR2(20)	NOT NULL	COMMENT '루틴이름'
);

DROP TABLE IF EXISTS `TB_GYM`;

CREATE TABLE `TB_GYM` (
	`GYM_NO`	NUMBER	NOT NULL,
	`GYM_NAME`	VARCHAR2(100)	NOT NULL,
	`GYM_LOCATION`	VARCHAR2(500)	NOT NULL
);

DROP TABLE IF EXISTS `TB_PT`;

CREATE TABLE `TB_PT` (
	`PT_NO`	NUMBER	NOT NULL,
	`GYM_NO`	NUMBER	NOT NULL,
	`TRAINER_NO`	NUMBER	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`PT_CATEGORY`	VARCHAR2(50)	NOT NULL	COMMENT '1웨이트, 2:채중감량,3:재활',
	`PT_PRICE`	NUMBER	NOT NULL	COMMENT '단위 원',
	`Field3`	LOB	NOT NULL,
	`Field4`	VARCHAR(255)	NOT NULL,
	`Field5`	VARCHAR(255)	NOT NULL,
	`Field6`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `TB_BOARD`;

CREATE TABLE `TB_BOARD` (
	`BOARD_NO`	NUMBER	NOT NULL,
	`BOARD_TITLE`	VARCHAR2(200)	NOT NULL,
	`BOARD_CONTENT`	VARCHAR2(1000)	NOT NULL,
	`BOARD_COUNT`	NUMBER	NOT NULL	DEFAULT 0,
	`BOARD_REPORT`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '없어져야한다고 생각합니다.',
	`MEMBER_NO`	NUMBER	NOT NULL,
	`BOARD_DATE`	SYSDATE	NOT NULL
);

DROP TABLE IF EXISTS `TB_RECOMMENT`;

CREATE TABLE `TB_RECOMMENT` (
	`RECOMMENT_NO`	NUMBER	NOT NULL,
	`BOARD_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`RECOMMENT_CONTENT`	VARCHAR2(300)	NOT NULL,
	`RECOMMENT_DATE`	SYSDATE	NOT NULL
);

DROP TABLE IF EXISTS `TB_ROUTINE_EXERCISE`;

CREATE TABLE `TB_ROUTINE_EXERCISE` (
	`ROUTINE_EXERCISE_NO`	NUMBER	NOT NULL,
	`EXERCISE_NO`	NUMBER	NOT NULL,
	`ROUTINE_EXERCISE_DAY`	VARCHAR(3)	NOT NULL	COMMENT 'DOMAIN:MON, THU,..
요일만 가능',
	`ROUTINE_NO`	NUMBER	NOT NULL,
	`ROUTINE_WEEK`	NUMBER	NULL,
	`ROUTINE_DAY`	VARCHAR(255)	NULL,
	`ROUTINE_EXERCISE_SET`	NUMBER	NULL	COMMENT '근력운동일때 입력',
	`ROUTINE_EXERCISE_REPEAT`	NUMBER	NULL	COMMENT '근력운동일때 입력',
	`ROUTINE_EXERCISE_WEIGHT`	NUMBER	NULL	COMMENT '근력운동일때 입력
단위:kg',
	`ROUTINE_EXERCISE_TIME`	NUMBER	NULL	COMMENT '유산소 운동중 시간으로 운동량이 결정되는 경우 단위: 분',
	`ROUTINE_EXERCISE_DISTANCE`	NUMBER	NULL	COMMENT '유산소 운동중 거리로 운동량이 결정되는 경우 단위: m',
	`Field2`	VARCHAR(255)	NULL	COMMENT '운동기록 테이블을 참조하면 알수 있지않나?',
	`Field3`	VARCHAR(255)	NULL	COMMENT '운동기록 테이블을 참조하면 알 수 잇지않나?',
	`Field5`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL	COMMENT '회의 후 결정',
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_PT_CALENDAR`;

CREATE TABLE `TB_PT_CALENDAR` (
	`PT_CALENDAR_NO`	NUMBER	NOT NULL,
	`PT_NO`	NUMBER	NOT NULL,
	`Field`	VARCHAR2(1)	NOT NULL	COMMENT '월, 화, 수, 목, 금, 토, 일',
	`Field2`	DATE	NOT NULL	COMMENT '일일 기준, 프로그램 시작 시간',
	`Field3`	DATE	NOT NULL	COMMENT '일일 기준, 프로그램 종료 시간'
);

DROP TABLE IF EXISTS `TB_TRAINER`;

CREATE TABLE `TB_TRAINER` (
	`TRAINER_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`GYM_NO`	NUMBER	NULL,
	`TRAINER_FILE`	LOB	NOT NULL	COMMENT 'URL',
	`TRAINER_CONFIRM`	VARCHAR(1)	NOT NULL	DEFAULT R	COMMENT 'T, F, R'
);

DROP TABLE IF EXISTS `TB_BLACKLIST`;

CREATE TABLE `TB_BLACKLIST` (
	`Key`	VARCHAR(255)	NOT NULL,
	`TRAINER_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`Field3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_FAVORITE`;

CREATE TABLE `TB_FAVORITE` (
	`Key`	VARCHAR(255)	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`BOARD_NO`	NUMBER	NOT NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_REVIEW`;

CREATE TABLE `TB_REVIEW` (
	`Key`	VARCHAR(255)	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`PT_NO`	NUMBER	NOT NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `.`;

CREATE TABLE `.` (
	`Key`	VARCHAR(255)	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '결재한 사람',
	`PT_NO`	NUMBER	NOT NULL	COMMENT 'PT 프로그램의 트레이너가 돈을 받음',
	`Field`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL,
	`Field11`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `Untitled2`;

CREATE TABLE `Untitled2` (
	`Key`	VARCHAR(255)	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_PHYSICAL_RECORD`;

CREATE TABLE `TB_PHYSICAL_RECORD` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`Field4`	DATE	NULL
);

DROP TABLE IF EXISTS `CopyOfTB_MEMBER`;

CREATE TABLE `CopyOfTB_MEMBER` (
	`MEMBER_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`MEMBER_PASSWORD`	VARCHAR2(20)	NOT NULL,
	`MEMBER_NICKNAME`	VARCHAR2(20)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR2(100)	NOT NULL,
	`MEMBER_NAME`	VARCHAR2(20)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR2(13)	NOT NULL,
	`MEMBER_AGE`	NUMBER	NULL,
	`PURPOSE_NAME`	VARCHAR2(20)	NULL,
	`CONCERN_NAME`	VARCHAR2(20)	NULL,
	`MEMBER_PHOTO`	LOB	NULL,
	`MEMBER_TRAINER`	VARCAHR2(1)	NOT NULL	DEFAULT F	COMMENT 'T: 트레이너F: 일반회원',
	`MEMBER_STATE`	VARCHAR2(1)	NOT NULL	DEFAULT N,
	`MEMBER_JOIN_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`MEMBER_LEAVE_DATE`	DATE	NULL
);

DROP TABLE IF EXISTS `Untitled3`;

CREATE TABLE `Untitled3` (
	`Key`	VARCHAR(255)	NOT NULL	COMMENT 'TB_BOARD BOARD_NO값이 입력됨',
	`Field4`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL	COMMENT '신고내역 백업테이블이 존재해야하나?'
);

DROP TABLE IF EXISTS `Untitled5`;

CREATE TABLE `Untitled5` (
	`Key`	VARCHAR(255)	NOT NULL,
	`BOARD_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_REPORT_LIST`;

CREATE TABLE `TB_REPORT_LIST` (
	`REPORT_NO`	NUMBER	NOT NULL,
	`RECOMMENT_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`REPORT_CONTENT`	VARCHAR2(300)	NOT NULL,
	`REPORT_DATE`	SYSDATE	NOT NULL
);

DROP TABLE IF EXISTS `CopyOfUntitled3`;

CREATE TABLE `CopyOfUntitled3` (
	`Key`	VARCHAR(255)	NOT NULL	COMMENT 'TB_BOARD BOARD_NO값이 입력됨',
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL	COMMENT '신고내역 백업테이블이 존재해야하나?'
);

DROP TABLE IF EXISTS `Untitled4`;

CREATE TABLE `Untitled4` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NULL,
	`Key3`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_RESERVATION_MEMBER`;

CREATE TABLE `TB_RESERVATION_MEMBER` (
	`Key`	NEMBER	NOT NULL,
	`PT_NO`	NUMBER	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL,
	`Field`	SYSDATE	NOT NULL,
	`Field2`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `TB_PT_FILE`;

CREATE TABLE `TB_PT_FILE` (
	`Key`	NUMBER	NOT NULL,
	`PT_NO`	NUMBER	NOT NULL,
	`Field`	LOB	NOT NULL
);

ALTER TABLE `TB_MEMBER` ADD CONSTRAINT `PK_TB_MEMBER` PRIMARY KEY (
	`MEMBER_NO`
);

ALTER TABLE `TB_EXERCISE` ADD CONSTRAINT `PK_TB_EXERCISE` PRIMARY KEY (
	`EXERCISE_NO`
);

ALTER TABLE `TB_EXERCISE_RECORD` ADD CONSTRAINT `PK_TB_EXERCISE_RECORD` PRIMARY KEY (
	`RECORD_NO`
);

ALTER TABLE `TB_ROUTINE` ADD CONSTRAINT `PK_TB_ROUTINE` PRIMARY KEY (
	`ROUTINE_NO`
);

ALTER TABLE `TB_GYM` ADD CONSTRAINT `PK_TB_GYM` PRIMARY KEY (
	`GYM_NO`
);

ALTER TABLE `TB_PT` ADD CONSTRAINT `PK_TB_PT` PRIMARY KEY (
	`PT_NO`
);

ALTER TABLE `TB_BOARD` ADD CONSTRAINT `PK_TB_BOARD` PRIMARY KEY (
	`BOARD_NO`
);

ALTER TABLE `TB_RECOMMENT` ADD CONSTRAINT `PK_TB_RECOMMENT` PRIMARY KEY (
	`RECOMMENT_NO`
);

ALTER TABLE `TB_ROUTINE_EXERCISE` ADD CONSTRAINT `PK_TB_ROUTINE_EXERCISE` PRIMARY KEY (
	`ROUTINE_EXERCISE_NO`
);

ALTER TABLE `TB_PT_CALENDAR` ADD CONSTRAINT `PK_TB_PT_CALENDAR` PRIMARY KEY (
	`PT_CALENDAR_NO`
);

ALTER TABLE `TB_TRAINER` ADD CONSTRAINT `PK_TB_TRAINER` PRIMARY KEY (
	`TRAINER_NO`
);

ALTER TABLE `TB_BLACKLIST` ADD CONSTRAINT `PK_TB_BLACKLIST` PRIMARY KEY (
	`Key`,
	`TRAINER_NO`,
	`MEMBER_NO`
);

ALTER TABLE `TB_FAVORITE` ADD CONSTRAINT `PK_TB_FAVORITE` PRIMARY KEY (
	`Key`,
	`MEMBER_NO`,
	`BOARD_NO`
);

ALTER TABLE `TB_REVIEW` ADD CONSTRAINT `PK_TB_REVIEW` PRIMARY KEY (
	`Key`,
	`MEMBER_NO`,
	`PT_NO`
);

ALTER TABLE `.` ADD CONSTRAINT `PK_.` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `PK_UNTITLED2` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TB_PHYSICAL_RECORD` ADD CONSTRAINT `PK_TB_PHYSICAL_RECORD` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfTB_MEMBER` ADD CONSTRAINT `PK_COPYOFTB_MEMBER` PRIMARY KEY (
	`MEMBER_NO`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `PK_UNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `PK_UNTITLED5` PRIMARY KEY (
	`Key`,
	`BOARD_NO`,
	`MEMBER_NO`
);

ALTER TABLE `TB_REPORT_LIST` ADD CONSTRAINT `PK_TB_REPORT_LIST` PRIMARY KEY (
	`REPORT_NO`,
	`RECOMMENT_NO`,
	`MEMBER_NO`
);

ALTER TABLE `CopyOfUntitled3` ADD CONSTRAINT `PK_COPYOFUNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `PK_UNTITLED4` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TB_RESERVATION_MEMBER` ADD CONSTRAINT `PK_TB_RESERVATION_MEMBER` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TB_PT_FILE` ADD CONSTRAINT `PK_TB_PT_FILE` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TB_EXERCISE_RECORD` ADD CONSTRAINT `FK_TB_EXERCISE_TO_TB_EXERCISE_RECORD_1` FOREIGN KEY (
	`EXERCISE_NO`
)
REFERENCES `TB_EXERCISE` (
	`EXERCISE_NO`
);

ALTER TABLE `TB_EXERCISE_RECORD` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_EXERCISE_RECORD_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_EXERCISE_RECORD` ADD CONSTRAINT `FK_TB_ROUTINE_EXERCISE_TO_TB_EXERCISE_RECORD_1` FOREIGN KEY (
	`ROUTINE_EXERCISE_NO`
)
REFERENCES `TB_ROUTINE_EXERCISE` (
	`ROUTINE_EXERCISE_NO`
);

ALTER TABLE `TB_ROUTINE` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_ROUTINE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_PT` ADD CONSTRAINT `FK_TB_GYM_TO_TB_PT_1` FOREIGN KEY (
	`GYM_NO`
)
REFERENCES `TB_GYM` (
	`GYM_NO`
);

ALTER TABLE `TB_PT` ADD CONSTRAINT `FK_TB_TRAINER_TO_TB_PT_1` FOREIGN KEY (
	`TRAINER_NO`
)
REFERENCES `TB_TRAINER` (
	`TRAINER_NO`
);

ALTER TABLE `TB_BOARD` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_BOARD_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_RECOMMENT` ADD CONSTRAINT `FK_TB_BOARD_TO_TB_RECOMMENT_1` FOREIGN KEY (
	`BOARD_NO`
)
REFERENCES `TB_BOARD` (
	`BOARD_NO`
);

ALTER TABLE `TB_RECOMMENT` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_RECOMMENT_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_ROUTINE_EXERCISE` ADD CONSTRAINT `FK_TB_EXERCISE_TO_TB_ROUTINE_EXERCISE_1` FOREIGN KEY (
	`EXERCISE_NO`
)
REFERENCES `TB_EXERCISE` (
	`EXERCISE_NO`
);

ALTER TABLE `TB_ROUTINE_EXERCISE` ADD CONSTRAINT `FK_TB_ROUTINE_TO_TB_ROUTINE_EXERCISE_1` FOREIGN KEY (
	`ROUTINE_NO`
)
REFERENCES `TB_ROUTINE` (
	`ROUTINE_NO`
);

ALTER TABLE `TB_PT_CALENDAR` ADD CONSTRAINT `FK_TB_PT_TO_TB_PT_CALENDAR_1` FOREIGN KEY (
	`PT_NO`
)
REFERENCES `TB_PT` (
	`PT_NO`
);

ALTER TABLE `TB_TRAINER` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_TRAINER_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_TRAINER` ADD CONSTRAINT `FK_TB_GYM_TO_TB_TRAINER_1` FOREIGN KEY (
	`GYM_NO`
)
REFERENCES `TB_GYM` (
	`GYM_NO`
);

ALTER TABLE `TB_BLACKLIST` ADD CONSTRAINT `FK_TB_TRAINER_TO_TB_BLACKLIST_1` FOREIGN KEY (
	`TRAINER_NO`
)
REFERENCES `TB_TRAINER` (
	`TRAINER_NO`
);

ALTER TABLE `TB_BLACKLIST` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_BLACKLIST_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_FAVORITE` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_FAVORITE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_FAVORITE` ADD CONSTRAINT `FK_TB_BOARD_TO_TB_FAVORITE_1` FOREIGN KEY (
	`BOARD_NO`
)
REFERENCES `TB_BOARD` (
	`BOARD_NO`
);

ALTER TABLE `TB_REVIEW` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_REVIEW_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_REVIEW` ADD CONSTRAINT `FK_TB_PT_TO_TB_REVIEW_1` FOREIGN KEY (
	`PT_NO`
)
REFERENCES `TB_PT` (
	`PT_NO`
);

ALTER TABLE `.` ADD CONSTRAINT `FK_TB_MEMBER_TO_._1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `.` ADD CONSTRAINT `FK_TB_PT_TO_._1` FOREIGN KEY (
	`PT_NO`
)
REFERENCES `TB_PT` (
	`PT_NO`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `FK_TB_MEMBER_TO_Untitled2_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_PHYSICAL_RECORD` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_PHYSICAL_RECORD_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `FK_TB_BOARD_TO_Untitled5_1` FOREIGN KEY (
	`BOARD_NO`
)
REFERENCES `TB_BOARD` (
	`BOARD_NO`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `FK_TB_MEMBER_TO_Untitled5_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_REPORT_LIST` ADD CONSTRAINT `FK_TB_RECOMMENT_TO_TB_REPORT_LIST_1` FOREIGN KEY (
	`RECOMMENT_NO`
)
REFERENCES `TB_RECOMMENT` (
	`RECOMMENT_NO`
);

ALTER TABLE `TB_REPORT_LIST` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_REPORT_LIST_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `FK_Untitled3_TO_Untitled4_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `Untitled3` (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `FK_CopyOfUntitled3_TO_Untitled4_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `CopyOfUntitled3` (
	`Key`
);

ALTER TABLE `TB_RESERVATION_MEMBER` ADD CONSTRAINT `FK_TB_PT_TO_TB_RESERVATION_MEMBER_1` FOREIGN KEY (
	`PT_NO`
)
REFERENCES `TB_PT` (
	`PT_NO`
);

ALTER TABLE `TB_RESERVATION_MEMBER` ADD CONSTRAINT `FK_TB_MEMBER_TO_TB_RESERVATION_MEMBER_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `TB_MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `TB_PT_FILE` ADD CONSTRAINT `FK_TB_PT_TO_TB_PT_FILE_1` FOREIGN KEY (
	`PT_NO`
)
REFERENCES `TB_PT` (
	`PT_NO`
);

